### ISSUE TITLE
Security Major Issue

### ISSUE THREAD

**Issue by proudloyaltier** [SyncoStories/Synco#12]
**How to test**

1. Open Synco and click create story
2. Open console and type in `localStorage.name = "<whatever name>"`
3.  Click create, it will now post with the modified name

**How to fix**

```
firebase.auth().onAuthStateChanged(function (user) {
  setInterval(function () {
    if (firebase.auth().currentUser) {
      if (localStorage.name !== user.email.replace("@fakeemail.com", "")) {
        signout()
      }
    }
  }, 100)
})
```

@TelOfLolth and @prealge This is a major security issue, place this code  at [Line 20 of db.js](https://github.com/SyncoStories/Synco/blob/8d19e05c56c12b216c060c84cf6d13a095c76c7d/db.js#L20`)

**Comment by neilgabrielson** [comment]
@luca1s Oh no! 😱
