### ISSUE TITLE
Admins

### ISSUE THREAD

**Issue by luca1s** [SyncoStories/Synco#6]
const admins can be .pushed to 

**To Reproduce**
1.  Enter admins.push("somebody") and check out the result

**Comment by luca1s** [comment]
@prealge and @coffee-media, consider making the admins in the DB

**Comment by control-alt-delete15** [comment]
That is a smart suggestion, and we have started,  but we will be focusing more on these types of things when we hit Beta.

**Comment by luca1s** [comment]
Alright! I'm writing code for it though!

**Comment by luca1s** [comment]
Fixed in [#7](https://github.com/SyncoStories/Synco/pull/7)

@TelOfLolth, could you review the PR

**Comment by neilgabrielson** [comment]
@phyllocrania, I tried to add admins to database, but it ended up giving hackers access if secure connection was not made.
